### ISSUE TITLE
Warning when no .boatsrc file exists

### ISSUE THREAD

**Issue by SergiAcrontum** [liffery-com/boats#31]
There should be a warning when the .boatsrc file doesn't exist.

It could be added here: https://github.com/johndcarmichael/boats/blob/master/src/GetCheckCorrectBoatsRc.ts#L11

**Comment by p-mcgowan** [comment]
yeah could do - It's not required, but I think I found myself wondering why a copy paste didn't work one time because the defaults we typically use are not the njk defaults

**Comment by johndcarmichael** [comment]
Yea, the njk defaults throw errors in editors that try to highlight errors in yml. 
The {{ }} generally leaves lots of red underline errors all over the shop where as <% %> do not which is why I opted for these as the defaults when i put the thing together.

Could also offer to inject a "stock" boatsrc file when one is not found

**Comment by p-mcgowan** [comment]
Ah - yeah generally I don't think editor config should change the defaults - but I'm just realizing that if you don't pass in a default config, the engine sets these as default.

I think it would make sense to not default the engine with those values, but rather output a default config (optionally with those). It is not correct (IMO) that the engine will run with different defaults than the underlying njk config.

**Comment by johndcarmichael** [comment]
I agree - a new release then that:

- checks for the existence of a boatsrc file 1st
- no rc file found? the tool outputs a default to the console complete with a little wording or links explaining what the defaults are
  -  this is also inline with other tools, eg eslint will not operate without a config set somewhere, rc file or in the packagejson

**Comment by p-mcgowan** [comment]
yeah, that would be cool - same thing with typescript - no tslint, it errors out and tells you to run `tsc --init`
